# config.yaml

# --- 公共配置 ---
max_seq_length: 128
num_classes: 2
train_path: "dataset/train.csv"
dev_path: "dataset/dev.csv"
test_path: "dataset/test.csv"

# --- Lab 2: BERT 配置 ---
lab2:
  model_name: "bert-base-chinese"
  batch_size: 16
  learning_rate: 2.0e-5
  num_epochs: 5
  result_dir: "results/lab2"
  model_save_path: "models/lab2_bert.pth"
  test_nrows: 1000

# --- Lab 3: Qwen 配置 ---
lab3:
  model_name: "Qwen/Qwen2.5-0.5B"  #
  batch_size: 32
  learning_rate: 1.0e-5 # LLM 微调通常LR要小
  num_epochs: 5
  result_dir: "results/lab3"
  model_save_path: "models/lab3_qwen.pth"
  test_nrows: 1000