[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "exp02-sentiment-classification"  
version = "0.1.0"     

dependencies = [
    torch==2.6.0
    transformers==4.50.3
    scikit-learn==0.24.2
    pandas==2.2.3
    numpy==1.22.4
]